// This file is auto-generated by @hey-api/openapi-ts

export type CreateTodoRequest = {
    title: null | string;
    notes: null | string;
    dueDate: null | string;
    sortOrder: null | string;
};

export type UpdateTodoRequest = {
    title: null | string;
    notes: null | string;
    dueDate: null | string;
    sortOrder: null | string;
    isCompleted: null | boolean;
    clearDueDate?: boolean;
};

export type GetScalarData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/scalar';
};

export type GetScalarResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiTodosData = {
    body?: never;
    path?: never;
    query?: {
        completed?: boolean;
        page?: string;
        pageSize?: string;
        sort?: string;
    };
    url: '/api/todos';
};

export type GetApiTodosResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostApiTodosData = {
    body: CreateTodoRequest;
    path?: never;
    query?: never;
    url: '/api/todos';
};

export type PostApiTodosResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type DeleteApiTodosByIdData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/todos/{id}';
};

export type DeleteApiTodosByIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiTodosByIdData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/todos/{id}';
};

export type GetApiTodosByIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PatchApiTodosByIdData = {
    body: UpdateTodoRequest;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/todos/{id}';
};

export type PatchApiTodosByIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type ClientOptions = {
    baseUrl: 'https://localhost:7448/' | (string & {});
};